# Generated by Django 4.2.4 on 2023-09-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='app_url',
            field=models.URLField(default='', max_length=100),
        ),
    ]
