# Generated by Django 4.2.4 on 2023-09-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_app_email_verification_token_app_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='email_verification_token',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
