# Generated by Django 4.2.4 on 2023-09-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_emailverification_remove_app_app_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='app_url',
            field=models.URLField(default='', max_length=100),
        ),
    ]
